name: mountain-os
description: A Fedora-powered Linux distro featuring a premium Mac-inspired aesthetic with a native Windows layout toggle.
base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - fedora-repos-ostree # Unlocks third-party repositories for atomic builds
      - chromium
      - okular
      - kate
      - spectacle
      - fastfetch

  - type: flatpak
    repo: https://flathub.org

  - type: script
    scripts:
      - setup-layouts.sh
