name: mountain-os
description: A Fedora-powered Linux distro featuring a premium Mac-inspired aesthetic with a native Windows layout toggle.
base-image: ghcr.io/fedora-ostree-desktops/kinoite
image-version: 41

modules:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox

  - type: rpm-ostree
    install:
      - google-chrome-stable
      - okular
      - kate
      - spectacle
      - fastfetch

  - type: script
    scripts:
      - setup-layouts.sh
