name: Build Mountain-OS Kilimanjaro
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-name: Build Mountain-OS ISO
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Custom Fedora Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
